os:
  - linux

branches:
  only:
    - master
    - issue-311

before_install:
- if [[ `node -v` == v0* ]]; then npm i -g npm@3; fi
- if [[ `node -v` != v0* ]]; then npm i -g npm@latest; fi

install:
- if [[ `node -v` == v0* ]]; then npm i; fi
- if [[ `node -v` != v0* ]]; then npm ci; fi

language: node_js
node_js:
  - "9"
  - "8"
  - "6"
  - "0.10"
#script: "npm run-script test"
script: "npm run-script test-cover"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
after_failure: "cat /home/travis/build/happner/happner/npm-debug.log"
